extension:
  - ts
exit: true # could be expressed as "no-exit: true"
recursive: true
reporter: spec
require:
  - 'test/helpers.ts'
  - 'ts-node/register'
  - 'reflect-metadata/Reflect'
slow: 5000
timeout: 75000 # same as "no-timeout: true" or "timeout: 0"
